import type { Metadata } from "next";
import {Barlow} from "next/font/google";
import {Roboto} from "next/font/google";
import "./globals.css";

const barlow = Barlow({subsets:['latin'],weight:['600'],variable:'--font-barlow'});
const roboto = Roboto({subsets:['latin'],weight:['400','500'],variable:'--font-roboto'});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
